spring.application.name=cefiishop

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/cefiishop?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=cefiishop_user
spring.datasource.password=cefiishop_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/cefiishop

# Ollama / Spring AI
spring.ai.ollama.base-url=http://localhost:11435
spring.ai.ollama.chat.model=phi3:mini

# Ollama Embedding Model
spring.ai.ollama.embedding.model=nomic-embed-text

# MongoDB Atlas Vector Store 
spring.ai.vectorstore.mongodb.uri=${MONGODB_ATLAS_URI:}
spring.ai.vectorstore.mongodb.password=${MONGODB_ATLAS_PWD:}
spring.ai.vectorstore.mongodb.user=${MONGODB_ATLAS_USER:}
spring.ai.vectorstore.mongodb.database-name=CefiiShopDB
spring.ai.vectorstore.mongodb.collection-name=vector_store
spring.ai.vectorstore.mongodb.initialize-schema=false
spring.ai.vectorstore.mongodb.index-name=vector_index
spring.ai.vectorstore.mongodb.embedding-dimension=768

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Chat options
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.top-k=50
spring.ai.ollama.chat.options.top-p=0.9
spring.ai.ollama.chat.options.num-predict=100
